# Generated by Django 5.0.7 on 2025-10-11 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=3)),
                ('quote', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=24)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['base', 'quote', '-fetched_at'], name='api_fxrate_base_58eddf_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER')], max_length=10)),
                ('price_per_gram', models.DecimalField(decimal_places=6, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['metal', '-fetched_at'], name='api_metalpr_metal_bf8762_idx')],
            },
        ),
    ]
