# Generated by Django 5.0.7 on 2025-10-11 15:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fxrate_metalprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('CASH', 'CASH')], max_length=6)),
                ('operation_type', models.CharField(choices=[('ADD', 'ADD'), ('WITHDRAW', 'WITHDRAW'), ('ZAKAT', 'ZAKAT')], max_length=8)),
                ('karat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_g', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('currency_code', models.CharField(blank=True, default='', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, default='', max_length=280)),
                ('invoice_image_url', models.URLField(blank=True, default='')),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_reason', models.CharField(blank=True, default='', max_length=180)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'asset_type'], name='api_transac_user_id_e78111_idx'), models.Index(fields=['user', 'asset_type', 'karat'], name='api_transac_user_id_816d82_idx'), models.Index(fields=['user', 'asset_type', 'currency_code'], name='api_transac_user_id_9a317c_idx'), models.Index(fields=['user', '-created_at'], name='api_transac_user_id_893f16_idx')],
            },
        ),
    ]
