# Generated by Django 5.0.7 on 2025-10-11 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='ZakatAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_group', models.CharField(choices=[('GOLD_PURE', 'GOLD_PURE'), ('SILVER', 'SILVER'), ('CASH_POOL', 'CASH_POOL')], max_length=16)),
                ('start_hijri_year', models.IntegerField(blank=True, null=True)),
                ('start_hijri_month', models.IntegerField(blank=True, null=True)),
                ('start_hijri_day', models.IntegerField(blank=True, null=True)),
                ('due_hijri_year', models.IntegerField(blank=True, null=True)),
                ('due_hijri_month', models.IntegerField(blank=True, null=True)),
                ('due_hijri_day', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_anchors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'asset_group'], name='api_zakatan_user_id_c1da47_idx')],
                'unique_together': {('user', 'asset_group')},
            },
        ),
    ]
